set nocompatible
filetype on
filetype plugin indent on
syntax enable
colorscheme slate

set number
set cursorline
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set showmatch
set laststatus=2
set noshowmode
set updatetime=100
set clipboard=unnamedplus
set incsearch
set hlsearch

"-------------Vundle (plugin manager)--------------
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
    Plugin 'VundleVim/Vundle.vim'
    Plugin 'tpope/vim-fugitive'
    Plugin 'https://github.com/airblade/vim-gitgutter.git'
    Plugin 'scrooloose/syntastic'
    Plugin 'scrooloose/nerdtree'
    Plugin 'git://git.wincent.com/command-t.git'
    Plugin 'itchyny/lightline.vim'
    Plugin 'Dimercel/todo-vim'
    Plugin 'Xuyuanp/nerdtree-git-plugin'
    Plugin 'rking/ag.vim'
    Plugin 'ctrlpvim/ctrlp.vim'
    Plugin 'vim-scripts/vim-auto-save.git'
    Plugin 'terryma/vim-multiple-cursors'
    Plugin 'majutsushi/tagbar'
call vundle#end()
:autocmd Filetype ruby set softtabstop=2
:autocmd Filetype ruby set sw=2
:autocmd Filetype ruby set ts=2

" Maps
nmap <F5> :TODOToggle<CR>
nmap <C-o> :NERDTreeToggle<CR>
