set nocompatible
filetype on
filetype plugin indent on
syntax enable
colorscheme slate

set number
set cursorline
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set showmatch
set laststatus=2
set noshowmode
set updatetime=100
set clipboard=unnamedplus
set incsearch
set hlsearch

"-------------Vundle (plugin manager)--------------
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
    Plugin 'VundleVim/Vundle.vim'
    Plugin 'tpope/vim-fugitive'
    Plugin 'airblade/vim-gitgutter'
    Plugin 'scrooloose/syntastic'
    Plugin 'scrooloose/nerdtree'
    Plugin 'scrooloose/nerdcommenter'
    Plugin 'git://git.wincent.com/command-t.git'
    Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
    Plugin 'itchyny/lightline.vim'
    Plugin 'Dimercel/todo-vim'
    Plugin 'Xuyuanp/nerdtree-git-plugin'
    Plugin 'mattn/emmet-vim'
    Plugin 'rking/ag.vim'
    Plugin 'ctrlpvim/ctrlp.vim'
    Plugin 'slim-template/vim-slim.git'
    Plugin 'vim-scripts/vim-auto-save.git'
    Plugin 'terryma/vim-multiple-cursors'
    Plugin 'majutsushi/tagbar'
    Plugin 'tpope/vim-rails'
    Plugin 'astashov/vim-ruby-debugger.git'
call vundle#end()
:autocmd Filetype ruby set softtabstop=2
:autocmd Filetype ruby set sw=2
:autocmd Filetype ruby set ts=2

" Maps
nmap <F5> :TODOToggle<CR>
nmap <C-o> :NERDTreeToggle<CR>
