export PATH=$HOME/bin:/usr/local/bin:$PATH
export ZSH="/home/alexey/.oh-my-zsh"

ZSH_THEME="bira-custom"

plugins=(
  git
  vi-mode   
  virtualenv
  tmux
)

source $ZSH/oh-my-zsh.sh

source "$HOME/.zsh_conf/aliases.zsh"

# rvm
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" 
