export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"
export GPG_TTY=$(tty)

ZSH_THEME="bira-shell"

plugins=(
  git
  mise
  fzf-tab
)

setopt interactivecomments

source $ZSH/oh-my-zsh.sh
